[package]
name = "smng"
version = "2.1.1"
authors = ["SchokiCoder <afschoknecht@gmail.com>"]
repository = "https://github.com/SchokiCoder/smng"
edition = "2018"
license = "GPLv3"
publish = false

[dependencies]
sqlite = "0.26.*"
chrono = "0.4.*"
term_size = "0.3.*"
