[package]
name = "smng"
version = "2.3.1"
authors = ["SchokiCoder <afschoknecht@gmail.com>"]
repository = "https://github.com/SchokiCoder/smng"
edition = "2018"
license = "GPLv3"
publish = false

[[bin]]
name = "smng-record"
path = "src/record.rs"

[dependencies]
sqlite = "0.26.*"
chrono = "0.4.*"
term_size = "0.3.*"
i18n_codegen = "0.1.*"
