[package]
name = "smng"
version = "0.1.0"
authors = ["SchokiCoder <afschoknecht@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.26.*"
chrono = "0.4.*"
