.TH "SMNG" "1" "18 June 2022" "smng 2.1.2" ""
.hy

.SH NAME
.PP
smng - SchokiManager

.SH SYNOPSIS
.PP
\f[B]smng\f[R] {{help | h} | {about | abt} | {add-project | ap}
\f[I]project_name\f[R] | {show-projects | sp} | {edit-project | ep}
\f[I]project_id\f[R] \f[I]project_name\f[R] | delete-project
\f[I]project_id\f[R] [\f[I]purge\f[R]] | {record | r}
\f[I]project_id\f[R] | status | {stop | s} \f[I]description\f[R] |
{add-record | ar} \f[I]project_id\f[R] \f[I]description\f[R]
\f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R] \f[I]hour\f[R]
\f[I]minute\f[R] \f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R]
\f[I]hour\f[R] \f[I]minute\f[R] | {edit-record-project | erp}
\f[I]record_id\f[R] \f[I]project_id\f[R] | {edit-record-begin | erb}
\f[I]record_id\f[R] \f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R]
\f[I]hour\f[R] \f[I]minute\f[R] | {edit-record-end | ere}
\f[I]record_id\f[R] \f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R]
\f[I]hour\f[R] \f[I]minute\f[R] | {edit-record-description | erd}
\f[I]record_id\f[R] \f[I]description\f[R] | delete-record
\f[I]record-id\f[R] | transfer-project-records
\f[I]source_project_id\f[R] \f[I]destination_project_id\f[R] |
{show-week | sw} [\f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R]] |
{show-month | sm} [\f[I]year\f[R] \f[I]month\f[R]] | {merge-db | mdb}
\f[I]source_database_path\f[R] \f[I]destination_database_path\f[R]}

.SH DESCRIPTION
.PP
Personal working time manager, to monitor the time you worked on each
project.

.SS help | h
.PP
Prints all help messages.

.SS about | abt
.PP
Prints information about the application.

.SS add-project | ap
.PP
Add a new project.

.SS show-projects | sp
.PP
Show all projects.

.SS edit-project | ep
.PP
Set project name of given project.

.SS delete-project
.PP
Delete given project and if "true" is given to argument \f[I]purge\f[R] delete all records from that project.

.SS record | r
.PP
Start recording work time on given project.

.SS status
.PP
Show current work status.

.SS stop | s
.PP
Stop recording work time with given description.

.SS add-record | ar
.PP
Add a new complete record.

.SS edit-record-project | erp
.PP
Set project of given record.

.SS edit-record-begin | erb
.PP
Set begin of given record.

.SS edit-record-end | ere
.PP
Set end of given record.

.SS edit-record-description | erd
.PP
Set description of given record.

.SS delete-record
.PP
Delete given record.

.SS transfer-project-records
.PP
Transfer all records from one project to another.

.SS show-week | sw
.PP
Show records of a given week or if none given current week.

.SS show-month | sm
.PP
Show records of a given month or if none given current month.

.SS merge-db | mdb
.PP
Merge projects and records of two databases.

.SH FILES
.PP
.I
/etc/smng.d/db_path

.SH COPYRIGHT
.PP
SchokiManager Copyright (C) 2021 Andy Frank Schoknecht
.PP
This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along
with this program.
If not, see <https://www.gnu.org/licenses/>.

.SH AUTHOR
Andy Frank Schoknecht
