.TH "SMNG" "1" "18 June 2022" "smng 2.1.2" ""
.hy

.SH NAME
.PP
smng - SchokiManager for personal work time management

.SH SYNOPSIS
.PP
\f[B]smng\f[R] COMMAND [ARGUMENTS]

.SH DESCRIPTION
.PP
Personal working time manager, to monitor the time you worked on each
project.

.SH COMMANDS
.SS Info Commands (Information on the program and it's usage)
.PP
\f[B]help | h\f[R]
.RS 4
Prints all help messages.

.PP
\f[B]about | abt\f[R]
.RS 4
Prints information about the application.
.RE

.SS Project Commands (adding, editing, deleting)
.PP
\f[B]add-project | ap\f[R] \f[I]project_name\f[R]
.RS 4
Add a new project.
.RE

.PP
\f[B]show-projects | sp\f[R]
.RS 4
Show all projects.
.RE

.PP
\f[B]edit-project | ep\f[R] \f[I]project_id\f[R] \f[I]project_name\f[R]
.RS 4
Set project name of given project.
.RE

.PP
\f[B]delete-project\f[R] \f[I]project_id\f[R] [\f[I]purge\f[R]]
.RS 4
Delete given project and if "true" is given to argument \f[I]purge\f[R] delete all records from that project.
.RE

.SS Record Commands (adding, editing, deleting)
.PP
\f[B]record | r\f[R] \f[I]project_id\f[R]
.RS 4
Start recording work time on given project.
.RE

.PP
\f[B]status\f[R]
.RS 4
Show current work status.
.RE

.PP
\f[B]stop | s\f[R] \f[I]description\f[R]
.RS 4
Stop recording work time with given description.
.RE

.PP
\f[B]add-record | ar\f[R] \f[I]project_id\f[R] \f[I]description\f[R] \f[I]begin_year\f[R] \f[I]begin_month\f[R] \f[I]begin_day\f[R] \f[I]begin_hour\f[R] \f[I]begin_minute\f[R] \f[I]end_year\f[R] \f[I]end_month\f[R] \f[I]end_day\f[R] \f[I]end_hour\f[R] \f[I]end_minute\f[R]
.RS 4
Add a new complete record.
.RE

.PP
\f[B]edit-record-project | erp\f[R] \f[I]record_id\f[R] \f[I]project_id\f[R]
.RS 4
Set project of given record.
.RE

.PP
\f[B]edit-record-begin | erb\f[R] \f[I]record_id\f[R] \f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R] \f[I]hour\f[R] \f[I]minute\f[R]
.RS 4
Set begin of given record.
.RE

.PP
\f[B]edit-record-end | ere\f[R] \f[I]record_id\f[R] \f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R] \f[I]hour\f[R] \f[I]minute\f[R]
.RS 4
Set end of given record.
.RE

.PP
\f[B]edit-record-description | erd\f[R] \f[I]record_id\f[R] \f[I]description\f[R]
.RS 4
Set description of given record.
.RE

.PP
\f[B]delete-record\f[R] \f[I]record_id\f[R]
.RS 4
Delete given record.
.RE

.PP
\f[B]transfer-project-records\f[R] \f[I]source_project_id\f[R] \f[I]destination_project_id\f[R]
.RS 4
Transfer all records from one project to another.
.RE

.SS Report Commands (show records)
.PP
\f[B]show-week | sw\f[R] [\f[I]year\f[R] \f[I]month\f[R] \f[I]day\f[R]]
.RS 4
Show records of a given week or if none given current week.
.RE

.PP
\f[B]show-month | sm\f[R] [\f[I]year\f[R] \f[I]month\f[R]]
.RS 4
Show records of a given month or if none given current month.
.RE

.SS Administration Commands (handling databases)
.PP
\f[B]merge-db | mdb\[R] \f[I]source_database_path\f[R] \f[I]destination_database_path\f[R]
.RS 4
Merge projects and records of two databases.
.RE

.SH FILES
.PP
.I
/etc/smng.d/db_path

.SH COPYRIGHT
.PP
SchokiManager Copyright (C) 2021 Andy Frank Schoknecht
.PP
This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along
with this program.
If not, see <https://www.gnu.org/licenses/>.

.SH AUTHOR
Andy Frank Schoknecht
