[package]
name = "smng-lib"
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sqlite.workspace = true
i18n_codegen.workspace = true

